version: "3.7"
services:
  app:
    build:
      args:
        user: tuxnir  # colocar el usuario linux en cuestion y su uid
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: resocentro
    container_name: resocentro-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - resocentronetwork

  db:
    image: mysql:5.7
    container_name: resocentro-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - resocentronetwork

  nginx:
    image: nginx:alpine
    container_name: resocentro-nginx
    restart: unless-stopped
    ports:
      - 8015:80 # Cambiar el puerto de entrada
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - resocentronetwork

networks:
  resocentronetwork:
    driver: bridge